# Generated by Django 3.0.4 on 2020-03-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200319_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(max_length=200)),
                ('ime', models.CharField(max_length=200)),
                ('trgovina', models.CharField(max_length=200)),
                ('valuta', models.CharField(max_length=200)),
                ('cijena', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
