# Generated by Django 3.0.4 on 2020-03-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_proizvod_valuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvod',
            name='proizvodjac',
            field=models.CharField(default='nema', max_length=200),
        ),
    ]
