# Generated by Django 3.0.4 on 2020-03-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_proizvod_proizvodjac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod',
            name='cijena',
            field=models.FloatField(),
        ),
    ]
